#!/bin/bash

echo $USER Welcome!
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
python3 -m pip install -r requirements.txt
xterm -hold -T "Quote of the Day" -e python3 $DIR/quote.py
xterm -hold -T "Times of India" -e python3 $DIR/toi.py
xterm -hold -T "Slashdot" -e python3 $DIR/slashdot.py
xterm -hold -T "Wikipedia" -e python3 $DIR/wikip.py
xterm -hold -T "Economic Times" -e python3 $DIR/et.py
xterm -hold -T "Random Country Wikipedia Article(because why not)" -e python3 $DIR/country.py
xterm -hold -T "Did You Know?" -e python3 $DIR/dyk.py
xterm -hold -T "Linux News" -e python3 $DIR/nuxnews.py
xterm -hold -T "Astronomy Pic of the Day" -e python3 $DIR/apod.py
